services:
  jc-frontend:
    container_name: jc-frontend
    build:
      context: ./next-app
      dockerfile: prod.Dockerfile
      args:
        ENV_VARIABLE: ${ENV_VARIABLE}
        NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
    restart: always
    env_file:
      - .env.production.local
    ports:
      - 3000:3000
    networks:
      - net

networks:
  net:
    external: true
