services:
  frontend:
    container_name: jcdev-frontend
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    # Set environment variables based on the .env file
    env_file:
      - .env.local
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/package.json:/app/package.json
      - ./frontend/.vscode:/app/.vscode
    restart: always
    ports:
      - 3000:3000

  # Add more containers below (nginx, postgres, etc.)
